services:
  - type: web
    name: complaints-registration-backend
    runtime: node
    rootDirectory: Backend
    buildCommand: npm install && npm run build && ls -R dist
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 3000
      - key: FRONTEND_PORT
        value: 5500
      - fromGroup: complaints-secrets # Assumes you have a secret group named this
