services:
  - type: web
    name: complaints-registration-backend
    runtime: node
    buildCommand: cd Backend && npm install && npm run build
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 3000
      - key: FRONTEND_PORT
        value: 5500
      - fromGroup: complaints-secrets # Assumes you have a secret group named this
